#!/bin/sh
set -e

ROOT="/dev/vdb"
UPGRADE_FILE="upgrade.f2fs.gz"


# initramfs setup
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp

mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

busybox --install -s


# upgrade rootfs
mount "$ROOT" /newroot
if [ -f "/newroot/$UPGRADE_FILE" ]; then
    echo "Upgrading rootfs..."

    set -o xtrace
    cp "/newroot/$UPGRADE_FILE" /tmp/
    umount /newroot
    dd if=/dev/zero of="$ROOT" bs=4096 count=65536
    zcat "/tmp/$UPGRADE_FILE" | dd of="$ROOT" bs=4096
    rm "/tmp/$UPGRADE_FILE"
    mount "$ROOT" /newroot
    set +o xtrace
fi

mount -t proc -o noexec,nosuid,nodev proc /newroot/proc
mount -t sysfs -o noexec,nosuid,nodev sysfs /newroot/sys
mount -t devtmpfs devtmpfs -o exec,nosuid,mode=0755,size=2M /newroot/dev

# ptys
[ -c /newroot/dev/ptmx ] || mknod -m 666 /newroot/dev/ptmx c 5 2
[ -d /newroot/dev/pts ] || mkdir -m 755 /newroot/dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /newroot/dev/pts

# shm
[ -d /newroot/dev/shm ] || mkdir /newroot/dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /newroot/dev/shm

mount -t tmpfs tmpfs /newroot/tmp

exec switch_root /newroot /sbin/init
